ReportDefinitions:
- reportName: CaseCategoryReport
  summary: This Report comprises different categories of issues for which the cases are being filed.
  version: 1.0.0
  moduleName: ilms-services
  sourceColumns:
  - name: name
    label: reports.case.casecategory
    type: string
    source: ilms_casecategory
  - name: registered
    label: reports.pgr.status.registered
    type: number
    source: seva
    linkedReport:
      reportName: DrillDownComplaintDetailByGrievanceType
      linkedColumn: _parent?reportName={reportName}&status={currentColumnName}&complainttype={name}  
  - name: inprocess
    label: reports.pgr.status.inprocess
    type: number
    source: completed
    linkedReport:
      reportName: DrillDownComplaintDetailByGrievanceType
      linkedColumn: _parent?reportName={reportName}&status=FORWARDED','PROCESSING&complainttype={name}
  - name: completed
    label: reports.pgr.status.completed
    type: number
    source: reopened
    linkedReport:
      reportName: DrillDownComplaintDetailByGrievanceType
      linkedColumn: _parent?reportName={reportName}&status=COMPLETED','WITHDRAWN&complainttype={name}
  - name: reopened
    label: reports.pgr.status.reopened
    type: number
    source: seva
    linkedReport:
      reportName: DrillDownComplaintDetailByGrievanceType
      linkedColumn: _parent?reportName={reportName}&status={currentColumnName}&complainttype={name}
  - name: rejected
    label: reports.pgr.status.rejected
    type: number
    source: seva
    linkedReport:
      reportName: DrillDownComplaintDetailByGrievanceType
      linkedColumn: _parent?reportName={reportName}&status={currentColumnName}&complainttype={name}
  - name: withinsla
    label: reports.pgr.status.withinsla
    type: number
    source: seva
    linkedReport:
      reportName: DrillDownComplaintDetailByGrievanceTypeWithINSLA
      linkedColumn: _parent?reportName={reportName}&complainttype={name}
  - name: beyondsla
    label: reports.pgr.status.beyondsla
    type: number
    source: seva
    linkedReport:
      reportName: DrillDownComplaintDetailByGrievanceTypeBeyondSLA
      linkedColumn: _parent?reportName={reportName}&complainttype={name}
  - name: issla
    label: reports.pgr.status.issla
    type: string
    source: seva
    showColumn: false
  searchParams:
  - name: fromDate
    label: reports.pgr.datefrom
    type: epoch
    source: seva
    isMandatory: true
  - name: toDate
    label: reports.pgr.dateto
    type: epoch
    source: seva
    isMandatory: true
  - name: complainttype
    label: reports.pgr.complainttype
    type: singlevaluelist
    pattern: http://pgr-master:8080/pgr-master/service/v1/_search?tenantId=$tenantid&keywords=complaint|$..serviceCode|$..serviceName
    source: seva
    isMandatory: true
  query: SELECT ctype.name,
    count(CASE WHEN cs.status::text = 'REGISTERED'::text THEN 1 ELSE NULL::integer END) AS registered,
    count(CASE WHEN cs.status::text = ANY (ARRAY['FORWARDED'::character varying::text, 'PROCESSING'::character varying::text, 'ONHOLD'::character varying::text]) THEN 1 ELSE NULL::integer END) AS inprocess,
    count(CASE WHEN cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text,'WITHDRAWN'::character varying::text]) THEN 1 ELSE NULL::integer END) AS completed,
    count(CASE WHEN cs.status::text = 'REOPENED'::text THEN 1 ELSE NULL::integer END) AS reopened,
    count(CASE WHEN cs.status::text ='REJECTED'::text THEN 1 ELSE NULL::integer END) AS rejected,
    sum(CASE WHEN (cs.status in ('COMPLETED',  'REJECTED','WITHDRAWN' , 'PROCESSING' , 'REGISTERED','REOPENED', 'ONHOLD','FORWARDED'))
    AND   (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS withinsla,
    sum(CASE WHEN (cs.status in ('COMPLETED',  'REJECTED','WITHDRAWN' , 'PROCESSING' , 'REGISTERED','REOPENED', 'ONHOLD', 'FORWARDED'))
    AND (now() - cs.createddate::timestamp   with time zone) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS beyondsla,
    CASE WHEN bool_or((cs.status::text = ANY (ARRAY['COMPLETED'::character
    varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text]))
    AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double
    precision)) THEN 'Yes'::text WHEN bool_or((cs.status::text <> ALL (ARRAY['COMPLETED'::character
    varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text]))
    AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval
    * ctype.slahours::double precision)) THEN 'Yes'::text ELSE 'No'::text END AS issla
    FROM submission cs, egpgr_complainttype ctype WHERE cs.servicecode = ctype.code
    and ctype.code = $complainttype and cs.createddate >= $fromDate and cs.createddate
    <= $toDate and cs.tenantid = $tenantid
    and ctype.tenantid = $tenantid
    GROUP BY ctype.name;


