ReportDefinitions:
  - reportName: CASEReport
    summary: Fetches report of cases
    version: 1.0.0
    moduleName: legal
    sourceColumns:
      - name: date
        label: reports.legal.date
        type: string
        source: eg_lg_case
        total: false
      - name: department
        label: reports.legal.deparment
        type: string
        source: eg_lg_case
        total: false
      - name: casecategory
        label: reports.legal.casecategory
        type: string
        source: eg_lg_case
        total: false
      - name: casestatus
        label: reports.legal.casestatus
        type: string
        source: eg_lg_case
        total: false
      - name: casetype
        label: reports.legal.casetype
        type: string
        source: eg_lg_case
        total: false
      - name: applicationstatus
        label: reports.legal.applicationstatus
        type: string
        source: eg_lg_case
        total: false
      - name: district
        label: reports.legal.district
        type: string
        source: eg_lg_court
        total: false
      - name: division
        label: reports.legal.division
        type: string
        source: eg_lg_court
        total: false
      - name: petitionertype
        label: reports.legal.petitionertype
        type: string
        source: eg_lg_case
        total: false
    searchParams:
      - name: applicationstatus
        label: reports.legal.applicationstatus
        type: singlevaluelist
        pattern: 'list://Pending At DEC:Pending At DEC,Pending at Reviewing Officer:Pending at Reviewing Officer,Pending at OICA Officer:Pending at OICA Officer,Pending at AO:Pending at AO,Pending for Counter Affidavit from hearing wf:Pending for Counter Affidavit from hearing wf,Pending for supplementary Affidavit from hearing wf:Pending for supplementary Affidavit from hearing wf,Judgement:Judgement,Judgement has been reviewed/appealed:Judgement has been reviewed/appealed,Judgement has been Complied:Judgement has been Complied,Inactive:Inactive'
        source: eg_lg_case
        isMandatory: false
        searchClause: AND legal_data.application_status = $applicationstatus
      - name: division
        label: reports.legal.boundary.division
        type: singlevaluelist
        source: eg_lg_court
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=egov-location&masterName=TenantBoundary|$.MdmsRes.egov-location.TenantBoundary[?(@.hierarchyType.name == 'JURISDICTION')].boundary.children[*].code|$.MdmsRes.egov-location.TenantBoundary[?(@.hierarchyType.name == 'JURISDICTION')].boundary.children[*].name
        isMandatory: false
        searchClause: AND legal_data.state || '.' || legal_data.division like $division || '%'
      - name: district
        label: reports.legal.boundary.district
        type: singlevaluelist
        source: eg_lg_court
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=egov-location&masterName=TenantBoundary|$.MdmsRes.egov-location.TenantBoundary[?(@.hierarchyType.name == 'JURISDICTION')].boundary.children[*].children[*].code|$.MdmsRes.egov-location.TenantBoundary[?(@.hierarchyType.name == 'JURISDICTION')].boundary.children[*].children[*].name
        isMandatory: false
        searchClause: AND legal_data.state || '.' || legal_data.division || '.' || legal_data.district like $district || '%'
      - name: casetype
        label: reports.legal.casetype
        type: singlevaluelist
        source: eg_lg_case
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=legal&masterName=CaseType|$.MdmsRes.legal.CaseType[*].code|$.MdmsRes.legal.CaseType[*].name
        isMandatory: false
        searchClause: AND legal_data.case_type = $casetype
      - name: casecategory
        label: reports.legal.casecategory
        type: singlevaluelist
        source: eg_lg_case
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=legal&masterName=CaseCategory|$.MdmsRes.legal.CaseCategory[*].code|$.MdmsRes.legal.CaseCategory[*].name
        isMandatory: false
        searchClause: AND legal_data.case_category = $casecategory
      - name: departmentname
        label: reports.legal.departmentname
        type: singlevaluelist
        source: eg_lg_case
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=legal&masterName=Department|$.MdmsRes.legal.Department[*].code|$.MdmsRes.legal.Department[*].name
        isMandatory: false
        searchClause: AND legal_data.department_name = $departmentname
      - name: fromDate
        label: reports.legal.datefrom
        type: epoch
        source: eg_lg_case
        isMandatory: false
        searchClause: AND legal_data.createdtime >= $fromDate
      - name: toDate
        label: reports.legal.dateto
        type: epoch
        source: eg_lg_case
        isMandatory: false
        searchClause: AND legal_data.createdtime <= $toDate

    query: |
      with legal_data as (SELECT
      	c.id,
        c.createdtime,
        p.department_name,
        c.case_category,
        c.case_status,
        c.case_type,
      c.application_status,
        court.district,
        court.division,
      court.state,
        p.petitioner_type     
        FROM public.eg_lg_case c
        LEFT JOIN eg_lg_case_party p ON p.case_id = c.id
        LEFT JOIN eg_lg_court court ON court.case_id = c.id)
        select
        legal_data.createdtime as date,
        legal_data.department_name as departmentname,
        legal_data.case_category as casecategory,
        legal_data.case_type as casetype,
        legal_data.application_status as applicationstatus,
        legal_data.case_status as casestatus,
        legal_data.district as district,
        legal_data.division as division,
        legal_data.state as state,
        legal_data.petitioner_type as petitionertype
        from legal_data
        WHERE 1=1
  

  - reportName: HearingReport
    summary: Fetches report of Hearing
    version: 1.0.0
    moduleName: legal
    sourceColumns:
      - name: courtnumber
        label: reports.legal.courtnumber
        type: string
        source: eg_lg_hearing
        total: false
      - name: bench
        label: reports.legal.bench
        type: string
        source: eeg_lg_hearing
        total: false
      - name: casenumber
        label: reports.legal.casenumber
        type: string
        source: eg_lg_hearing
        total: false
      - name: hearingDate
        label: reports.legal.hearingDate
        type: string
        source: eg_lg_hearing
        total: false
      - name: nextHearingDate
        label: reports.legal.nextHearingDate
        type: string
        source: eg_lg_hearing
        total: false
      - name: status
        label: reports.legal.status
        type: string
        source: eg_lg_hearing
        total: false
    searchParams:
      - name: fromDate
        label: reports.legal.datefrom
        type: epoch
        source: eg_lg_hearing
        isMandatory: false
        searchClause: AND legal_data.createdtime >= $fromDate
      - name: toDate
        label: reports.legal.dateto
        type: epoch
        source: eg_lg_hearing
        isMandatory: false
        searchClause: AND legal_data.createdtime <= $toDate

    query: |
      with legal_data as (SELECT 
      court_number, 
      bench, 
      hearing_date, 
      case_number,
      next_hearing_date,
      createdtime,
      status
      FROM
      public.eg_lg_hearing)
      select
        legal_data.court_number as courtnumber,
        legal_data.bench as bench,
        legal_data.hearing_date as hearingDate,
        legal_data.case_number as casenumber,
        legal_data.next_hearing_date as nextHearingDate,
        legal_data.status as status
        from legal_data 
        WHERE 1=1 


  - reportName: LegalReport
    summary: Fetches report of Entire Case
    version: 1.0.0
    moduleName: legal
    sourceColumns:
      - name: casenumber
        label: reports.legal.casenumber
        type: string
        source: eg_lg_case
        total: false
      - name: casetype
        label: reports.legal.casetype
        type: string
        source: eeg_lg_case
        total: false
      - name: casecategory
        label: reports.legal.casecategory
        type: string
        source: eg_lg_case
        total: false
      - name: filingate
        label: reports.legal.filingDate
        type: string
        source: eg_lg_case
        total: false
      - name: applicationstatus
        label: reports.legal.applicationstatus
        type: string
        source: eg_lg_case
        total: false
      - name: hearingnumber
        label: reports.legal.hearingnumber
        type: string
        source: eg_lg_hearing
        total: false
      - name: courtroomnumber
        label: reports.legal.courtroomnumber
        type: string
        source: eg_lg_hearing
        total: false
      - name: nextHearingDate
        label: reports.legal.nextHearingDate
        type: string
        source: eg_lg_hearing
        total: false
      - name: fineimposeddate
        label: reports.legal.fineimposeddate
        type: string
        source: eg_lg_payment
        total: false
      - name: fineduedate
        label: reports.legal.fineduedate
        type: string
        source: eg_lg_payment
        total: false
      - name: fineammount
        label: reports.legal.fineammount
        type: string
        source: eg_lg_payment
        total: false
      - name: district
        label: reports.legal.district
        type: string
        source: eg_lg_court
        total: false
      - name: division
        label: reports.legal.division
        type: string
        source: eg_lg_court
        total: false
      - name: decisionstatus
        label: reports.legal.decisionstatus
        type: string
        source: eg_lg_judgement
        total: false
      - name: orderdate
        label: reports.legal.orderdate
        type: string
        source: eg_lg_judgement
        total: false
    searchParams:
      - name: fromDate
        label: reports.legal.datefrom
        type: epoch
        source: eg_lg_case
        isMandatory: false
        searchClause: AND legal_data.createdtime >= $fromDate
      - name: toDate
        label: reports.legal.dateto
        type: epoch
        source: eg_lg_case
        isMandatory: false
        searchClause: AND legal_data.createdtime <= $toDate

    query: |
      WITH legal_data AS (
          SELECT
          c.id,
          c.case_number,
          c.case_type,
          c.case_category,
          c.filing_date,
          c.application_status,
          c.createdtime,
          h.hearing_number,
          h.court_number,
          h.hearing_date,
          h.next_hearing_date,
          h.createdtime as hearing_createdtime,
          p.fine_imposed_date,
          p.fine_due_date,
          p.fine_amount,
          court.district,
          court.division,
          j.decision_status,
          j.order_date,
          j.order_type,
          ROW_NUMBER() OVER (PARTITION BY c.id ORDER BY h.createdtime DESC) AS rn
          FROM
          eg_lg_case c
          LEFT JOIN eg_lg_hearing h ON h.case_id = c.id
          LEFT JOIN eg_lg_judgement j ON j.case_id = c.id
          LEFT JOIN eg_lg_payment p ON p.case_id = c.id
          LEFT JOIN eg_lg_court court ON court.case_id = c.id
        )
        SELECT
        legal_data.case_number AS casenumber,
        legal_data.case_type AS casetype,
        legal_data.case_category AS casecategory,
        legal_data.filing_date AS filingdate,
        legal_data.application_status AS applicationstatus,
        legal_data.hearing_number AS hearingnumber,
        legal_data.court_number AS courtnumber,
        legal_data.next_hearing_date AS nexthearingdate,
        legal_data.fine_imposed_date AS fineimposeddate,
        legal_data.fine_due_date AS fineduedate,
        legal_data.fine_amount AS fineammount,
        legal_data.district AS district,
        legal_data.division AS division,
        legal_data.decision_status AS decisionstatus,
        legal_data.order_date AS orderdate
        FROM
        legal_data
        WHERE
        legal_data.rn = 1 

